server:
  tomcat:
    uri-encoding: UTF-8
  port: 8520
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
spring:
#  生产者配置
  kafka:
    bootstrap-servers: 51.14.200.67:11190
    consumer:
      auto-commit-interval: 100
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 500
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual_immediate
      poll-timeout: 500S
#  消费者配置

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_light?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://127.0.0.1:3306/car_4.0?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: senken
  web:
    resources:
      #图片文件的总目录
      #例子
      #//upload//haikang图片数据
      static-locations: file:/home/pi/image
#海康上传文件格式要求
#//upload//haikang//2021-10-11//1564894561654//图片数据

logging:
  file:
    path: ./log

#海康图片物理路径
upload_file: D:\upload\haiKang

#当前资源路径地址


#当前服务器ip
#当前java程序端口
this:
  ip: 44.144.22.110
  port: ${server.port}
  url_path: D://upload/
  sum: 1000
  #上传以萨人脸开关
  upload_face: true
  #上传以萨车牌开关
  upload_car: true
  #上传海康接口开关
  upload_hai_kang: false
  #注册开关
  register: true
  #保活开关
  keepAlive: true
YI_SA_IP: 51.14.200.67
YI_SA_PORT: 2530
USERNAMES: admin
PASSWORDS: 123456
#上传不同数据的时间间隔
SEND_YI_SA_FACE: 0/20 * * * * ?
SEND_YI_SA_CAR: 0/20 * * * * ?
SEND_HAI_KANG: 0/10 * * * * ?

#http://44.144.6.38:9080/VIID/MotorVehicles
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl













